#!/usr/bin/env python3
"""Derive the per-world, per-preset jumpstart tree.

    tools/jumpstart/presets/<preset>.yaml   WORLD-AGNOSTIC tier definition
    tools/jumpstart/worlds/tier-policy.yaml WORLD-AGNOSTIC tier -> settings policy
    tools/jumpstart/worlds/<World>/world.yaml   WORLD-SPECIFIC facts
        |
        +--> tools/jumpstart/worlds/<World>/<preset>/
                 settings/world-modifiers.env    generated
                 settings/overrides.yaml         generated
                 settings/chest-manifest.yaml    generated
                 keys.yaml                       generated
                 charactertemplate.yml           generated
                 spawn.yaml                      generated by `spawn` (needs terrain)
                 blueprints/                     created empty, owned by others
                 placements.yaml                 NOT written; read if present

Nothing here is hand-maintained. Every generated file carries a provenance
header naming the three inputs, and `--check` re-derives in memory and diffs, so
a hand edit or a stale regenerate is detectable rather than silent.

    derive.py list
    derive.py build <World> [--preset NAME ...]
    derive.py check <World> [--preset NAME ...]
    derive.py spawn <World> [--preset NAME ...] [--check]

`build` writes; `check` never writes and exits 1 on drift.

The template's `spawn:` block is the one coordinate this tree emits, and it is
the one thing it cannot derive from YAML alone: a coordinate is only usable if
the ground under it is dry. `spawn` probes Valheim's own generator at 1 m
through tools/jumpstart/blueprints/run_patchscan.sh, picks a point that is
verifiably on land next to the placement, and records the evidence in
spawn.yaml. `build` and `check` then need no terrain at all: they cross-check
spawn.yaml against the CURRENT `solved` blocks, which is the check whose absence
put a character in the sea -- the solver re-solved, the base moved, and nothing
compared the two.
"""
from __future__ import annotations

import argparse
import importlib.util
import math
import os
import re
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

import yaml

HERE = Path(__file__).resolve().parent
JUMPSTART = HERE.parent
REPO = JUMPSTART.parent.parent
POLICY_PATH = HERE / "tier-policy.yaml"

GENERATED_BY = "tools/jumpstart/worlds/derive.py"
# Files this tool owns. Anything else in a preset directory belongs to someone
# else and is never written, moved or deleted here.
OWNED = (
    "settings/world-modifiers.env",
    "settings/overrides.yaml",
    "settings/chest-manifest.yaml",
    "keys.yaml",
    "charactertemplate.yml",
)


def _load_jumpstart():
    """Import jumpstart.py as a module so preset loading has exactly one impl.

    Re-parsing the preset schema here is how the two directories would drift, so
    the loader is borrowed rather than copied. jumpstart.py guards its CLI behind
    __main__, so importing it runs nothing.
    """
    spec = importlib.util.spec_from_file_location("jumpstart", JUMPSTART / "jumpstart.py")
    if spec is None or spec.loader is None:  # pragma: no cover - defensive
        raise SystemExit(f"cannot import {JUMPSTART / 'jumpstart.py'}")
    module = importlib.util.module_from_spec(spec)
    sys.modules["jumpstart"] = module
    spec.loader.exec_module(module)
    return module


js = _load_jumpstart()


# ==========================================================================
# inputs
# ==========================================================================
@dataclass
class World:
    name: str
    root: Path
    raw: dict

    @property
    def baseline_modifiers(self) -> dict[str, str]:
        return dict((self.raw.get("baseline") or {}).get("world_modifiers") or {})

    @property
    def pinned_modifiers(self) -> list[str]:
        """Modifier keys the world owns; a preset cannot move these."""
        return list((self.raw.get("baseline") or {}).get("pinned") or [])

    @property
    def launch_preset(self) -> str:
        return str((self.raw.get("baseline") or {}).get("launch_preset") or "Normal")

    @property
    def slots(self) -> int:
        return int((self.raw.get("inventory") or {}).get("slots") or 32)

    @property
    def stack_table_path(self) -> Path:
        rel = (self.raw.get("inventory") or {}).get("stack_table")
        if not rel:
            return Path()
        # Paths in world.yaml are written relative to VALHEIM_ROOT, which is where
        # the deployed profiles live; they are not repo paths.
        return Path(js.DEFAULT_VALHEIM_ROOT) / rel

    @property
    def stack_fallbacks(self) -> dict[str, int]:
        raw = (self.raw.get("inventory") or {}).get("stack_fallbacks") or {}
        return {str(k): int(v) for k, v in raw.items()}


def load_world(name: str) -> World:
    root = HERE / name
    path = root / "world.yaml"
    if not path.exists():
        raise SystemExit(f"no such world: {name!r} (looked for {path})")
    raw = yaml.safe_load(path.read_text("utf-8"))
    if not isinstance(raw, dict) or raw.get("world") != name:
        raise SystemExit(f"{path}: 'world' must be {name!r}")
    return World(name=name, root=root, raw=raw)


def load_policy() -> dict:
    raw = yaml.safe_load(POLICY_PATH.read_text("utf-8"))
    if not isinstance(raw, dict):
        raise SystemExit(f"{POLICY_PATH}: policy must be a YAML mapping")
    return raw


STACK_RE = re.compile(r"^([A-Za-z0-9_]+)_max_stack\s*=\s*(\d+)\s*$")


def load_stacks(world: World) -> tuple[dict[str, int], dict[str, int]]:
    """(measured stack sizes, inferred fallbacks). Missing table is not fatal."""
    measured: dict[str, int] = {}
    path = world.stack_table_path
    if path and path.exists():
        for line in path.read_text("utf-8", errors="replace").splitlines():
            m = STACK_RE.match(line.strip())
            if m:
                measured[m.group(1)] = int(m.group(2))
    return measured, world.stack_fallbacks


def load_placements(preset_dir: Path) -> dict | None:
    """BlueprintHunt's placements.yaml, if it exists. Read-only, never written."""
    path = preset_dir / "placements.yaml"
    if not path.exists():
        return None
    raw = yaml.safe_load(path.read_text("utf-8")) or {}
    if not isinstance(raw, dict):
        raise SystemExit(f"{path}: expected a YAML mapping")
    return raw


def solved_placements(placements: dict | None) -> dict[str, dict]:
    """Placements that currently carry a solved site, by id."""
    out: dict[str, dict] = {}
    for pl in (placements or {}).get("placements") or []:
        sol = (pl or {}).get("solved") or {}
        if "x" in sol and "z" in sol:
            out[str(pl.get("id"))] = pl
    return out


def load_container_capacity(placements: dict | None) -> int | None:
    """Chest slot capacity of the placed base, if placements.yaml reports it."""
    if not placements:
        return None
    # BlueprintHunt's schema, counted out of the blueprint object list:
    #   containers: {by_prefab: {<piece>: n}, containers: n, slots_floor: n}
    # `slots_floor` is the conservative slot total, which is the number worth
    # comparing an overflow manifest against.
    total = 0
    seen = False
    for placement in placements.get("placements") or []:
        containers = (placement or {}).get("containers") or {}
        if "slots_floor" in containers:
            seen = True
            total += int(containers["slots_floor"])
    return total if seen else None


# ==========================================================================
# spawn
# ==========================================================================
# Sea level in WorldGenerator.GetHeight units. MEASURED three independent ways
# on the Pirate68 artefacts, because getting this number wrong is exactly how a
# jumpstart character ends up swimming:
#   1. Biome bands, 6.9 M cells of the 8 m grid. Swamp spans 27.46..33.84 with a
#      29.84 median -- a narrow band straddling 30, which is what a swamp is.
#      Ocean cells are clamped at <= 4.00, and 4.00 = 0.02 * 200: GetBiome's
#      oceanLevel is baseHeight 0.02 and GetHeight returns baseHeight * 200, so
#      that clamp is the ocean FLOOR some 26 m down, not the surface.
#   2. The 12,301-instance ZoneSystem location dump. Every land location type
#      floors at 30.50..31.11 (Grave1 30.50, Ruin1 31.02, StoneHouse4 31.04,
#      Crypt2 31.11) -- Valheim places land locations with m_minAltitude 1 above
#      the water. The ocean ones (ShipWreck01..04) sit at 29.0..30.9.
#   3. 30 / 200 = 0.15, the baseHeight the generator treats as the shoreline.
# tools/jumpstart/blueprints/site_finder.py uses WATER_LEVEL = 0.0, i.e. the
# ocean-floor clamp read as the surface, so its `water_dist_m` measures the
# distance to 30-m-deep water and its sites can sit below the waterline while
# passing. Reported to that file's owner; nothing here depends on those numbers.
SEA_LEVEL_M = 30.0

# Freeboard the written coordinate must clear the water plane by. Valheim's own
# rule for putting a land location down is m_minAltitude = 1 m (MEASURED above:
# the land-location floor is 30.50..31.11), so 1 m is the game's own definition
# of "on land" and 2 m is that with a metre of slack for the 1 m lattice, for the
# terrain the blueprint's flatten pass will move, and for shoreline waves. It is
# deliberately not higher: Swamp land tops out at +3.84 m world-wide on this
# seed, and a floor no swamp can meet is a floor that deletes Swamp spawns.
SPAWN_FREEBOARD_M = 2.0
# A spawn is a point; a player is not. Every 1 m sample within this radius must
# clear the water by SPAWN_DISC_FREEBOARD_M, so a candidate cannot be a one-cell
# pinnacle in a bog with water on all sides.
SPAWN_DISC_R_M = 4.0
SPAWN_DISC_FREEBOARD_M = 0.5
# Stand-off from the blueprint's own footprint, so nobody wakes up inside a wall
# once the base is materialised. Measured against footprint_xzy_m rotated by the
# placement's yaw -- the real rectangle, not the square the solver searched with.
SPAWN_FOOTPRINT_CLEAR_M = 6.0
# How far outside that rectangle a spawn may sit and still count as "at the
# base". 120 m is 20-25 s of walking and well inside view distance; past that the
# honest answer is that this site has no dry ground next to it and the placement
# needs re-solving, which is what the recorded refusal says.
SPAWN_SEARCH_MAX_M = 120.0
# The approach, sampled every metre from the spawn to the nearest point on the
# footprint rectangle. The ground must stay above water -- a spawn separated
# from its base by a channel is a spawn on the wrong side of a swim -- and must
# not step more than this per metre, which is what rules out a ravine.
SPAWN_PATH_FREEBOARD_M = 0.5
SPAWN_PATH_STEP_M = 1.5
# y is written as ceil(terrain + this). Up, never down: rounding a spawn down
# puts the player inside the ground, and ServerCharacters hands the triple
# straight to the client.
SPAWN_Y_CLEAR_M = 1.0
# Taste, stated so it can be argued with. Nearness first (the operator's
# complaint was distance and water, in that order), then the side the building
# faces (the placement's own declared intent), then dryness beyond the floor.
SPAWN_WEIGHTS = {"near": 0.45, "facade": 0.30, "dry": 0.25}
# 1 m is the resolution Valheim builds its terrain mesh at, so it is the only
# honest resolution for a point verdict. The 8 m seedscan grid is NOT usable
# here at any margin: run_scan.sh leaves pregeneration off, so its heights are
# river-free, and MEASURED at the operator's own spawn it reports 30.17 where the
# true river-aware height is 26.74 -- a 3.4 m error that flips the verdict from
# "land" to "three metres under water".
SPAWN_PROBE_STEP_M = 1.0
# Slack beyond the search radius so the disc and the approach of the outermost
# candidate are still inside the probed window.
SPAWN_PROBE_PAD_M = 12.0
# Candidates whose approach is actually walked, best score first. The score is a
# proxy for the approach verdict, and a truncated ranking is a bad proxy: the
# best-scoring 1000 points of a 40,000-point ring are all within a few metres of
# each other, so a cap alone would test one spot 1000 times and then refuse. The
# tries are therefore THINNED -- at most one per SPAWN_TRY_SEPARATION_M cell --
# which spends the same bounded work spread across the whole ring. MEASURED: a
# 120 m walk is ~150 samples, so 1024 tries is ~150 k samples, tenths of a
# second, and the refusal message reports how many were walked.
SPAWN_APPROACH_TRIES = 1024
SPAWN_TRY_SEPARATION_M = 8.0

SPAWN_FILE = "spawn.yaml"
PATCHSCAN = JUMPSTART / "blueprints" / "run_patchscan.sh"


def _site_finder():
    """blueprints/site_finder.py, imported by path.

    Borrowed for load_patches() only: one VHPATCH1 reader for the whole repo, so
    a patch cannot be indexed one way here and another way there. numpy and
    scipy arrive with it, which is why this is lazy -- `list`, `build` and
    `check` must stay runnable on a bare Python with no terrain artefacts.
    """
    path = JUMPSTART / "blueprints" / "site_finder.py"
    spec = importlib.util.spec_from_file_location("site_finder", path)
    if spec is None or spec.loader is None:  # pragma: no cover - defensive
        raise SystemExit(f"cannot import {path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules["site_finder"] = module
    spec.loader.exec_module(module)
    return module


def footprint_half_extents(pl: dict) -> tuple[float, float]:
    """Half extents of the blueprint's own footprint, in its own axes.

    placements.yaml records footprint_xzy_m as the measured x/z/y extent of the
    unrotated blueprint; the yaw is applied separately, when a point is taken
    into the building's frame. The requirement's search square is the fallback
    only when the real footprint is missing.
    """
    fp = pl.get("footprint_xzy_m") or []
    if len(fp) >= 2:
        return float(fp[0]) / 2.0, float(fp[1]) / 2.0
    side = float((pl.get("requirement") or {}).get("footprint_m", 56.0))
    return side / 2.0, side / 2.0


def placement_yaw(pl: dict) -> float:
    return float((pl.get("rotation") or {}).get("yaw", 0.0) or 0.0)


def _to_local(px, pz, cx: float, cz: float, yaw_deg: float):
    """World delta from a placement's centre, rotated into the building's axes.

    Same convention as placements.yaml's own rotation_convention: Unity euler Y,
    +yaw turning the building clockwise seen from above, so the world delta is
    rotated by -yaw. Scalars in the audit, numpy planes in the probe -- one
    implementation, so the two can never disagree about which way is forward.
    """
    a = math.radians(yaw_deg)
    ca, sa = math.cos(a), math.sin(a)
    dx, dz = px - cx, pz - cz
    return dx * ca - dz * sa, dx * sa + dz * ca


def rect_distance(px, pz, cx: float, cz: float, hx: float, hz: float, yaw_deg: float):
    """Distance from a point to a yawed rectangle; 0 inside it."""
    lx, lz = _to_local(px, pz, cx, cz, yaw_deg)
    ox = abs(lx) - hx
    oz = abs(lz) - hz
    if hasattr(ox, "clip"):
        ox = ox.clip(min=0.0)
        oz = oz.clip(min=0.0)
        return (ox * ox + oz * oz) ** 0.5
    return math.hypot(max(ox, 0.0), max(oz, 0.0))


def rect_nearest(px: float, pz: float, cx: float, cz: float, hx: float, hz: float, yaw_deg: float):
    """The point on the rectangle's edge a walker would head for."""
    lx, lz = _to_local(px, pz, cx, cz, yaw_deg)
    nx = min(max(lx, -hx), hx)
    nz = min(max(lz, -hz), hz)
    a = math.radians(yaw_deg)
    ca, sa = math.cos(a), math.sin(a)
    return cx + (nx * ca + nz * sa), cz + (-nx * sa + nz * ca)


def patch_origin(patch: dict) -> tuple[int, int]:
    """World coordinate of patch sample (0, 0), which MUST be an integer.

    PatchScan samples (i, j) at cx - half + j*step + step/2. With step 1, an
    integer half and a half-integer centre that lands exactly on integer world
    coordinates -- which is the whole point. `spawn` takes integers, so the
    verdict has to be taken at the integer that gets written, not half a cell
    away from it; the candidates here ARE lattice points, so there is no rounding
    after the fact to invalidate them.
    """
    x0 = patch["cx"] - patch["half"] + patch["step"] * 0.5
    z0 = patch["cz"] - patch["half"] + patch["step"] * 0.5
    if abs(x0 - round(x0)) > 1e-6 or abs(z0 - round(z0)) > 1e-6:
        raise SystemExit(
            f"patch at ({patch['cx']}, {patch['cz']}) half={patch['half']} "
            f"step={patch['step']} does not sample integer coordinates"
        )
    return int(round(x0)), int(round(z0))


def patch_rows(world: World, presets: list) -> list[tuple[str, float, float, float, float]]:
    """One 1 m patch request per solved placement, centred on the placement."""
    rows: list[tuple[str, float, float, float, float]] = []
    for preset in presets:
        placements = load_placements(world.root / preset.name)
        for pid, pl in sorted(solved_placements(placements).items()):
            hx, hz = footprint_half_extents(pl)
            half = float(
                math.ceil(math.hypot(hx, hz) + SPAWN_SEARCH_MAX_M + SPAWN_PROBE_PAD_M)
            )
            sol = pl["solved"]
            rows.append(
                (
                    f"{preset.name}#{pid}",
                    round(float(sol["x"])) + 0.5,
                    round(float(sol["z"])) + 0.5,
                    half,
                    SPAWN_PROBE_STEP_M,
                )
            )
    return rows


def patch_covers(rows, patches: dict) -> bool:
    """Does this patch file actually answer the request we are about to make?"""
    for pid, cx, cz, half, step in rows:
        p = patches.get(pid)
        if p is None:
            return False
        if abs(p["cx"] - cx) > 1e-3 or abs(p["cz"] - cz) > 1e-3:
            return False
        if abs(p["step"] - step) > 1e-6 or p["half"] + 1e-3 < half:
            return False
    return True


def run_patchscan(seed: str, rows, patch: Path, vh_src: str, sandbox: str | None) -> None:
    req = patch.with_suffix(".req.tsv")
    patch.parent.mkdir(parents=True, exist_ok=True)
    req.write_text(
        "".join(f"{i}\t{cx}\t{cz}\t{half}\t{step}\n" for i, cx, cz, half, step in rows),
        "utf-8",
    )
    env = dict(os.environ, VH_SRC=vh_src, SEED=seed, REQ=str(req), OUT=str(patch))
    if sandbox:
        env["SANDBOX"] = sandbox
    # Boots the dedicated server in an rsync'd sandbox on its own port and
    # savedir, exactly as the placement solver's 1 m pass does. Nothing live.
    subprocess.run([str(PATCHSCAN)], env=env, check=True)


def dry_approach(patch: dict, origin: tuple[int, int], sx: int, sz: int, tx: float, tz: float) -> dict:
    """Walk 1 m at a time from the spawn to the footprint edge and report.

    Intermediate steps are not lattice points, so each is read at its nearest
    integer sample: at most 0.71 m of horizontal error on a walk whose purpose is
    to find water and cliffs, both of which are metres wide. The endpoints are
    exact -- the spawn IS a lattice point.

    Any water at all fails the walk, INCLUDING water at the base end. A base
    site that is itself below the water plane cannot have a spawn that is both
    next to it and joined to it by dry ground, and the right answer there is to
    refuse and re-solve the site, not to ship the least-bad point: a missing
    spawn is a visible gap, a wet one is a bug that reaches the operator.
    """
    height = patch["height"]
    n = patch["n"]
    x0, z0 = origin
    span = math.hypot(tx - sx, tz - sz)
    steps = max(1, int(math.ceil(span)))
    free: list[float] = []
    for k in range(steps + 1):
        t = k / steps
        j = int(round(sx + (tx - sx) * t)) - x0
        i = int(round(sz + (tz - sz) * t)) - z0
        if not (0 <= i < n and 0 <= j < n):
            return {"ok": False, "reason": "approach leaves the probed window"}
        free.append(float(height[i, j]) - SEA_LEVEL_M)
    worst_wet = min(free)
    if worst_wet < SPAWN_PATH_FREEBOARD_M:
        return {
            "ok": False,
            "reason": f"approach crosses water ({worst_wet:.2f} m relative to the water plane)",
        }
    steps_m = [abs(free[k + 1] - free[k]) for k in range(len(free) - 1)]
    worst = max(steps_m) if steps_m else 0.0
    if worst > SPAWN_PATH_STEP_M:
        return {"ok": False, "reason": f"approach steps {worst:.2f} m in one metre"}
    return {
        "ok": True,
        "length_m": round(span, 1),
        "min_freeboard_m": round(worst_wet, 2),
        "max_step_m": round(worst, 2),
        "dry_to_footprint_edge": True,
    }


def probe_spawn(patch: dict, pl: dict) -> dict:
    """Pick this placement's spawn out of its 1 m patch, or refuse and say why.

    Every candidate is an integer world coordinate that is: at least
    SPAWN_FOOTPRINT_CLEAR_M outside the blueprint's rotated footprint and at most
    SPAWN_SEARCH_MAX_M outside it; SPAWN_FREEBOARD_M above the water plane at the
    exact written point; above SPAWN_DISC_FREEBOARD_M across a SPAWN_DISC_R_M
    disc; and joined to the footprint edge by a metre-by-metre walk that stays
    out of the water and off cliffs. Nothing is inferred -- if no such point
    exists the return value is a refusal carrying the numbers that explain it.
    """
    import numpy as np
    from scipy import ndimage

    sol = pl["solved"]
    bx, bz = float(sol["x"]), float(sol["z"])
    hx, hz = footprint_half_extents(pl)
    yaw = placement_yaw(pl)
    origin = patch_origin(patch)
    x0, z0 = origin
    n = patch["n"]
    free = patch["height"].astype(np.float64) - SEA_LEVEL_M
    X, Z = np.meshgrid(
        x0 + np.arange(n, dtype=np.float64), z0 + np.arange(n, dtype=np.float64)
    )
    edge = rect_distance(X, Z, bx, bz, hx, hz, yaw)
    r = int(SPAWN_DISC_R_M)
    dy, dx = np.mgrid[-r : r + 1, -r : r + 1]
    # A poisoned border means a candidate whose disc leaves the probed window
    # loses, rather than winning on evidence that was never gathered.
    disc = ndimage.minimum_filter(
        free, footprint=(dx * dx + dy * dy) <= r * r, mode="constant", cval=-1e9
    )
    ring = (edge >= SPAWN_FOOTPRINT_CLEAR_M) & (edge <= SPAWN_SEARCH_MAX_M)
    dry = free >= SPAWN_FREEBOARD_M
    ok = ring & dry & (disc >= SPAWN_DISC_FREEBOARD_M)
    base_free = float(free[round(bz) - z0, round(bx) - x0])
    nearest_dry = None
    if dry.any():
        nearest_dry = round(
            float(np.hypot(X[dry] - bx, Z[dry] - bz).min()), 1
        )
    counts = {
        "in_ring": int(ring.sum()),
        "ring_and_freeboard": int((ring & dry).sum()),
        "ring_freeboard_and_disc": int(ok.sum()),
        "nearest_freeboard_m": nearest_dry,
        "base_freeboard_m": round(base_free, 2),
    }
    if not ok.any():
        return {"refused": _refusal(counts), "counts": counts}

    iz, ix = np.nonzero(ok)
    cand_x = (x0 + ix).astype(np.int64)
    cand_z = (z0 + iz).astype(np.int64)
    cand_edge = edge[iz, ix]
    cand_free = free[iz, ix]
    cand_disc = disc[iz, ix]
    # Bearing agreement with the side the building faces. placements.yaml's yaw
    # convention makes the facade normal (sin yaw, cos yaw) in world axes, which
    # is the same vector the placement solver offsets its own naive point along.
    a = math.radians(yaw)
    fx, fz = math.sin(a), math.cos(a)
    dxv = cand_x - bx
    dzv = cand_z - bz
    norm = np.hypot(dxv, dzv)
    norm[norm == 0] = 1.0
    facade = ((dxv * fx + dzv * fz) / norm + 1.0) / 2.0
    near = 1.0 - np.clip(
        (cand_edge - SPAWN_FOOTPRINT_CLEAR_M)
        / max(SPAWN_SEARCH_MAX_M - SPAWN_FOOTPRINT_CLEAR_M, 1e-9),
        0.0,
        1.0,
    )
    dryness = np.clip(cand_free / (2.0 * SPAWN_FREEBOARD_M), 0.0, 1.0)
    score = (
        SPAWN_WEIGHTS["near"] * near
        + SPAWN_WEIGHTS["facade"] * facade
        + SPAWN_WEIGHTS["dry"] * dryness
    )
    order = np.argsort(-score)
    rejected: dict[str, int] = {}
    tried = 0
    seen_cells: set[tuple[int, int]] = set()
    sep = max(1.0, SPAWN_TRY_SEPARATION_M)
    for k in order:
        if tried >= SPAWN_APPROACH_TRIES:
            break
        sx, sz = int(cand_x[k]), int(cand_z[k])
        cell = (int(math.floor(sx / sep)), int(math.floor(sz / sep)))
        if cell in seen_cells:
            continue
        seen_cells.add(cell)
        tried += 1
        tx, tz = rect_nearest(float(sx), float(sz), bx, bz, hx, hz, yaw)
        walk = dry_approach(patch, origin, sx, sz, tx, tz)
        if not walk["ok"]:
            rejected[walk["reason"]] = rejected.get(walk["reason"], 0) + 1
            continue
        terrain = round(float(cand_free[k]) + SEA_LEVEL_M, 2)
        return {
            "point": {
                "x": sx,
                # ceil of the RECORDED terrain, not of the raw float, so `check`
                # re-deriving y from this file gets the same integer.
                "y": int(math.ceil(terrain + SPAWN_Y_CLEAR_M)),
                "z": sz,
                "base": str(pl.get("id")),
                "base_xz": [bx, bz],
                "base_y": float(sol.get("y")) if sol.get("y") is not None else None,
                "base_freeboard_m": round(base_free, 2),
                "terrain_y": terrain,
                "spawn_freeboard_m": round(terrain - SEA_LEVEL_M, 2),
                "disc_min_freeboard_m": round(float(cand_disc[k]), 2),
                "dist_to_base_m": round(math.hypot(sx - bx, sz - bz), 1),
                "dist_to_footprint_edge_m": round(float(cand_edge[k]), 1),
                "footprint_half_extents_m": [hx, hz],
                "yaw": yaw,
                "facade_agreement": round(float(facade[k]), 3),
                "score": round(float(score[k]), 3),
                "approach": {kk: vv for kk, vv in walk.items() if kk != "ok"},
                "candidates_considered": int(ok.sum()),
            }
        }
    counts["approach_rejections"] = rejected
    counts["approach_tried"] = tried
    return {
        "base": str(pl.get("id")),
        "base_xz": [bx, bz],
        "refused": _refusal(counts),
        "counts": counts,
    }


def _refusal(counts: dict) -> str:
    """One sentence an operator can act on, built from the numbers we measured."""
    base_free = counts["base_freeboard_m"]
    submerged = (
        f" The placement itself is {abs(base_free):.2f} m BELOW the water plane, so no point "
        "next to it can be reached without swimming: re-solve the SITE."
        if base_free < 0
        else ""
    )
    if not counts["in_ring"]:
        return (
            f"no integer coordinate lies {SPAWN_FOOTPRINT_CLEAR_M:.0f}-"
            f"{SPAWN_SEARCH_MAX_M:.0f} m outside the footprint inside the probed window."
            + submerged
        )
    near = counts["nearest_freeboard_m"]
    if not counts["ring_and_freeboard"]:
        where = (
            f"{near:.0f} m from the placement centre"
            if near is not None
            else "nowhere in the probed window"
        )
        return (
            f"no ground with {SPAWN_FREEBOARD_M:.0f} m of freeboard within "
            f"{SPAWN_SEARCH_MAX_M:.0f} m of the footprint; the nearest such ground is "
            f"{where}." + submerged
        )
    if not counts["ring_freeboard_and_disc"]:
        return (
            f"{counts['ring_and_freeboard']} dry point(s) in range, none holding "
            f"{SPAWN_DISC_FREEBOARD_M:.1f} m of freeboard across a {SPAWN_DISC_R_M:.0f} m disc "
            "-- every one of them is a pinnacle or a shoreline." + submerged
        )
    reasons = ", ".join(
        f"{v}x {k}" for k, v in sorted(counts.get("approach_rejections", {}).items())
    )
    return (
        f"{counts['ring_freeboard_and_disc']} dry point(s) in range, and none of the "
        f"{counts.get('approach_tried', 0)} best is walkable to the footprint edge "
        f"({reasons or 'no candidate reached the approach test'})." + submerged
    )


def render_spawn(world: World, preset, results: list[dict]) -> str:
    points = [r["point"] for r in results if "point" in r]
    refused = [
        {"base": r["base"], "reason": r["refused"], "base_xz": r["base_xz"], "measured": r["counts"]}
        for r in results
        if "refused" in r
    ]
    doc = [
        f"# GENERATED by {GENERATED_BY} -- do not edit.",
        f"# Verified spawn points for world {world.name}, preset {preset.name}.",
        "# Inputs:",
        f"#   tools/jumpstart/worlds/{world.name}/{preset.name}/placements.yaml   "
        "(`solved` sites, BlueprintHunt)",
        f"#   tools/jumpstart/worlds/{world.name}/world.yaml   (seed)",
        "#   Valheim's own WorldGenerator, sampled at "
        f"{SPAWN_PROBE_STEP_M:g} m through",
        "#   tools/jumpstart/blueprints/run_patchscan.sh (rivers and lakes included)",
        f"# Regenerate:  tools/jumpstart/worlds/derive.py spawn {world.name}",
        "#",
        "# This file exists so the coordinate that ships is a MEASURED one. The",
        "# placement solver's own `spawn_points:` block is NOT used: it is a naive",
        "# footprint-and-yaw offset with no terrain test at all, and MEASURED on",
        "# Ulfsland/Pirate68 its pre-bonemass point sampled 4.2 m UNDER the water",
        "# plane. `derive.py check` re-checks every point below against the CURRENT",
        "# `solved` blocks, so a re-solve that moves a base makes this file loudly",
        "# stale instead of silently wrong.",
        "",
    ]
    body = {
        "world": world.name,
        "preset": preset.name,
        "seed": world.raw.get("seed"),
        "sea_level_m": SEA_LEVEL_M,
        "probe": {
            "source": "tools/jumpstart/blueprints/run_patchscan.sh (VHPATCH1)",
            "step_m": SPAWN_PROBE_STEP_M,
            "sampled_at": "integer world coordinates -- the verdict is taken at the coordinate "
            "that gets written, after rounding, not half a cell away",
        },
        "criteria": {
            "freeboard_m": SPAWN_FREEBOARD_M,
            "disc_radius_m": SPAWN_DISC_R_M,
            "disc_freeboard_m": SPAWN_DISC_FREEBOARD_M,
            "footprint_clearance_m": SPAWN_FOOTPRINT_CLEAR_M,
            "max_from_footprint_m": SPAWN_SEARCH_MAX_M,
            "approach_freeboard_m": SPAWN_PATH_FREEBOARD_M,
            "approach_max_step_m": SPAWN_PATH_STEP_M,
            "y_clearance_m": SPAWN_Y_CLEAR_M,
        },
        "points": points,
    }
    if refused:
        body["refused"] = refused
    return "\n".join(doc) + yaml.safe_dump(body, sort_keys=False, width=88, allow_unicode=True)


def load_spawn_file(preset_dir: Path) -> dict | None:
    path = preset_dir / SPAWN_FILE
    if not path.exists():
        return None
    raw = yaml.safe_load(path.read_text("utf-8")) or {}
    if not isinstance(raw, dict):
        raise SystemExit(f"{path}: expected a YAML mapping")
    return raw


def audit_spawn(
    world: World, preset, placements: dict | None, spawn_doc: dict | None
) -> tuple[list[dict], list[str]]:
    """Cross-check spawn.yaml against the CURRENT placements.yaml.

    This is the check that did not exist, and its absence is how a character was
    dropped in the sea: the `solved` blocks are re-solved by one tool, the
    template is rendered by another, and nothing ever compared the two. Pure
    geometry plus the evidence the probe recorded, so it needs no Valheim server
    and no 34 MB grid -- it runs wherever `check` runs.
    """
    problems: list[str] = []
    solved = solved_placements(placements)
    regen = f"tools/jumpstart/worlds/derive.py spawn {world.name} --preset {preset.name}"
    tag = f"{world.name}/{preset.name}"
    if not solved:
        if spawn_doc and (spawn_doc.get("points") or spawn_doc.get("refused")):
            problems.append(
                f"{tag}: {SPAWN_FILE} records spawn work but placements.yaml has no solved "
                f"placement left. Delete it or re-solve. Run: {regen}"
            )
        return [], problems
    if spawn_doc is None:
        problems.append(
            f"{tag}: placements.yaml has {len(solved)} solved placement(s) and no {SPAWN_FILE}, "
            f"so no spawn has ever been verified against terrain. Run: {regen}"
        )
        return [], problems
    seed = str(world.raw.get("seed"))
    if str(spawn_doc.get("seed")) != seed:
        problems.append(
            f"{tag}: {SPAWN_FILE} was probed on seed {spawn_doc.get('seed')!r} but world.yaml "
            f"says {seed!r}. Every coordinate in it belongs to a different world. Run: {regen}"
        )
    if float(spawn_doc.get("sea_level_m", -1)) != SEA_LEVEL_M:
        problems.append(
            f"{tag}: {SPAWN_FILE} was verified against sea level "
            f"{spawn_doc.get('sea_level_m')}, this tool now uses {SEA_LEVEL_M}. Run: {regen}"
        )
    points = [p for p in (spawn_doc.get("points") or []) if isinstance(p, dict)]
    refused = [r for r in (spawn_doc.get("refused") or []) if isinstance(r, dict)]
    covered: set[str] = set()

    def base_moved(entry: dict, what: str) -> bool:
        base = str(entry.get("base"))
        pl = solved.get(base)
        if pl is None:
            problems.append(
                f"{tag}: {what} was derived from placement {base!r}, which no longer has a "
                f"solved site. Run: {regen}"
            )
            return True
        sol = pl["solved"]
        rec = entry.get("base_xz") or [None, None]
        now_x, now_z = float(sol["x"]), float(sol["z"])
        if rec[0] is None or abs(float(rec[0]) - now_x) > 0.01 or abs(float(rec[1]) - now_z) > 0.01:
            moved = (
                math.hypot(float(rec[0]) - now_x, float(rec[1]) - now_z)
                if rec[0] is not None
                else float("nan")
            )
            problems.append(
                f"{tag}: {what} was verified against {base} at "
                f"({rec[0]}, {rec[1]}) but that placement is now at ({now_x}, {now_z}), "
                f"{moved:.0f} m away. The terrain verdict no longer applies to the spawn that "
                f"would ship. Run: {regen}"
            )
            return True
        return False

    for pt in points:
        base = str(pt.get("base"))
        covered.add(base)
        x, y, z = pt.get("x"), pt.get("y"), pt.get("z")
        what = f"spawn ({x}, {y}, {z})"
        if not all(isinstance(v, int) for v in (x, y, z)):
            problems.append(
                f"{tag}: {what} is not three integers, which is the only thing "
                f"ServerCharacters' `spawn:` accepts. Run: {regen}"
            )
            continue
        if base_moved(pt, what):
            continue
        pl = solved[base]
        terrain = pt.get("terrain_y")
        if not isinstance(terrain, (int, float)):
            problems.append(f"{tag}: {what} records no terrain_y, so it is unverified. Run: {regen}")
            continue
        margin = round(float(terrain) - SEA_LEVEL_M, 2)
        if margin + 1e-9 < SPAWN_FREEBOARD_M:
            problems.append(
                f"{tag}: {what} stands on terrain {terrain}, which is {margin} m above the "
                f"water plane ({SEA_LEVEL_M}); the floor is {SPAWN_FREEBOARD_M} m. That is a "
                f"spawn in the water. Run: {regen}"
            )
        want_y = int(math.ceil(float(terrain) + SPAWN_Y_CLEAR_M))
        if y != want_y:
            problems.append(
                f"{tag}: {what} should have y={want_y} for terrain {terrain} "
                f"(ceil(terrain + {SPAWN_Y_CLEAR_M})). Run: {regen}"
            )
        disc = pt.get("disc_min_freeboard_m")
        if not isinstance(disc, (int, float)) or float(disc) + 1e-9 < SPAWN_DISC_FREEBOARD_M:
            problems.append(
                f"{tag}: {what} records {disc} m of freeboard across its "
                f"{SPAWN_DISC_R_M} m disc; the floor is {SPAWN_DISC_FREEBOARD_M} m. Run: {regen}"
            )
        hx, hz = footprint_half_extents(pl)
        sol = pl["solved"]
        edge = rect_distance(
            float(x), float(z), float(sol["x"]), float(sol["z"]), hx, hz, placement_yaw(pl)
        )
        if edge + 1e-6 < SPAWN_FOOTPRINT_CLEAR_M:
            problems.append(
                f"{tag}: {what} is {edge:.1f} m from the {2 * hx:g}x{2 * hz:g} m footprint of "
                f"{base}; the stand-off is {SPAWN_FOOTPRINT_CLEAR_M} m, so a player would wake "
                f"up inside the building. Run: {regen}"
            )
        if edge - 1e-6 > SPAWN_SEARCH_MAX_M:
            problems.append(
                f"{tag}: {what} is {edge:.1f} m outside {base}'s footprint, past the "
                f"{SPAWN_SEARCH_MAX_M} m limit. Run: {regen}"
            )
        walk = pt.get("approach") or {}
        if walk.get("max_step_m") is None or float(walk["max_step_m"]) > SPAWN_PATH_STEP_M:
            problems.append(
                f"{tag}: {what} records an approach that steps {walk.get('max_step_m')} m in "
                f"one metre; the limit is {SPAWN_PATH_STEP_M} m. Run: {regen}"
            )
        if (
            walk.get("min_freeboard_m") is None
            or float(walk["min_freeboard_m"]) + 1e-9 < SPAWN_PATH_FREEBOARD_M
        ):
            problems.append(
                f"{tag}: {what} records an approach whose lowest ground is "
                f"{walk.get('min_freeboard_m')} m over the water plane; the floor is "
                f"{SPAWN_PATH_FREEBOARD_M} m, so the walk to the base goes through water. "
                f"Run: {regen}"
            )

    for entry in refused:
        covered.add(str(entry.get("base")))
        base_moved(entry, f"the recorded refusal for {entry.get('base')!r}")

    for base in sorted(set(solved) - covered):
        problems.append(
            f"{tag}: placement {base} has a solved site with neither a verified spawn nor a "
            f"recorded refusal in {SPAWN_FILE}. Run: {regen}"
        )
    return [p for p in points if all(isinstance(p.get(k), int) for k in "xyz")], problems


# ==========================================================================
# derivation
# ==========================================================================
def item_map(preset) -> tuple[dict[str, int], list[tuple[str, str, int]], list[str]]:
    """Collapse the preset's three item buckets into the map the template needs.

    Returns (summed map, ordered [(bucket, prefab, count)], duplicate prefabs).
    The buckets are LISTS and the template field is a MAP, so a prefab named in
    two buckets would be silently overwritten by a naive conversion. pre-kall and
    deepnorth-sandbox both do that, so the counts are summed and the collisions
    reported.
    """
    merged: dict[str, int] = {}
    ordered: list[tuple[str, str, int]] = []
    dupes: list[str] = []
    for bucket in ("kit", "chain_items", "materials"):
        for row in preset.raw.get(bucket) or []:
            prefab = str(row["prefab"])
            count = int(row.get("count", 1))
            if prefab in merged:
                dupes.append(prefab)
            merged[prefab] = merged.get(prefab, 0) + count
            ordered.append((bucket, prefab, count))
    return merged, ordered, sorted(set(dupes))


def slot_cost(prefab: str, count: int, measured: dict[str, int], fallbacks: dict[str, int]) -> tuple[int, str]:
    if count <= 1:
        # One item is one slot whatever the stack size, so this needs no table.
        return 1, "trivial"
    if prefab in measured:
        return -(-count // measured[prefab]), "measured"
    if prefab in fallbacks:
        return -(-count // fallbacks[prefab]), "inferred"
    return count, "unknown"


@dataclass
class Partition:
    carried: dict[str, int]
    carried_slots: int
    overflow: dict[str, int]
    overflow_slots: int
    detail: dict[str, tuple[int, str, str]]  # prefab -> (slots, evidence, bucket)
    dupes: list[str]
    unknown: list[str]


def partition(preset, world: World, measured: dict[str, int], fallbacks: dict[str, int]) -> Partition:
    """Split the preset's items into what a 32-slot grid can hold and what cannot.

    Priority is kit, then chain_items, then the cheapest materials, because the
    kit is what makes a character read as "at this tier" and materials are also
    reachable from a chest. An entry that does not fit is skipped and the next is
    tried -- deterministic, and it wastes no slots -- rather than truncating the
    whole tail.
    """
    merged, ordered, dupes = item_map(preset)

    detail: dict[str, tuple[int, str, str]] = {}
    first_bucket: dict[str, str] = {}
    for bucket, prefab, _count in ordered:
        first_bucket.setdefault(prefab, bucket)
    unknown: list[str] = []
    for prefab, count in merged.items():
        slots, evidence = slot_cost(prefab, count, measured, fallbacks)
        if evidence == "unknown":
            unknown.append(prefab)
        detail[prefab] = (slots, evidence, first_bucket[prefab])

    rank = {"kit": 0, "chain_items": 1, "materials": 2}
    order = sorted(
        merged,
        key=lambda p: (rank[detail[p][2]], detail[p][0] if detail[p][2] == "materials" else 0, p),
    )

    carried: dict[str, int] = {}
    used = 0
    for prefab in order:
        cost = detail[prefab][0]
        if used + cost <= world.slots:
            carried[prefab] = merged[prefab]
            used += cost
    overflow = {p: c for p, c in merged.items() if p not in carried}
    return Partition(
        carried=carried,
        carried_slots=used,
        overflow=overflow,
        overflow_slots=sum(detail[p][0] for p in overflow),
        detail=detail,
        dupes=dupes,
        unknown=sorted(unknown),
    )


def effective_modifiers(preset, world: World, policy: dict) -> tuple[dict[str, str], list[str]]:
    """Baseline, overlaid with the preset's non-Default modifiers, except pins.

    A PINNED key belongs to the world and a preset cannot move it. Without pins
    the merge is backwards for exactly the value the operator asked to have one
    home: every `pre-*` preset declares `Resources: More`, so an unpinned merge
    would let nine tier files quietly downgrade the world's `MuchMore` baseline.
    Pinning keeps the fleet's resource rate and portal policy a single edit in
    world.yaml, while leaving the keys no preset shares -- Raids, DeathPenalty,
    Combat -- free for a preset to set.
    """
    ignore = str((policy.get("world_modifiers") or {}).get("ignore_value") or "Default")
    pinned = set(world.pinned_modifiers)
    effective = dict(world.baseline_modifiers)
    changes: list[str] = []
    for key in js.MODIFIER_KEYS:
        value = preset.world_modifiers.get(key)
        if not value or value == ignore:
            continue
        previous = effective.get(key)
        if key in pinned:
            if previous != value:
                changes.append(
                    f"{key}: preset asks {value}, world pins {previous} -- world wins"
                )
            continue
        effective[key] = value
        if previous is None:
            changes.append(f"{key}: (unset) -> {value}  [preset]")
        elif previous != value:
            changes.append(f"{key}: {previous} -> {value}  [preset]")
    return effective, changes


def applicable_rules(preset, policy: dict) -> list[dict]:
    out = []
    for rule in policy.get("server_config_rules") or []:
        by_tier = rule.get("by_tier") or {}
        if preset.tier in by_tier:
            out.append((rule, by_tier[preset.tier]))
    return out


# ==========================================================================
# rendering
# ==========================================================================
def provenance(world: World, preset, kind: str) -> list[str]:
    return [
        f"# GENERATED by {GENERATED_BY} -- do not edit.",
        f"# {kind} for world {world.name}, preset {preset.name} (tier {preset.tier}).",
        "# Inputs:",
        f"#   tools/jumpstart/presets/{preset.name}.yaml   (tier definition, world-agnostic)",
        "#   tools/jumpstart/worlds/tier-policy.yaml      (tier -> settings policy, world-agnostic)",
        f"#   tools/jumpstart/worlds/{world.name}/world.yaml   (this world's facts)",
        "# Regenerate:  tools/jumpstart/worlds/derive.py build " + world.name,
    ]


def render_modifiers(world: World, preset, policy: dict) -> str:
    effective, changes = effective_modifiers(preset, world, policy)
    args = " ".join(f"-modifier {k} {effective[k]}" for k in js.MODIFIER_KEYS if k in effective)
    lines = provenance(world, preset, "World modifiers (launch arguments, not config keys)")
    lines += [
        "#",
        "# These are process arguments: they belong in valheim.env's SERVER_ARGS and",
        "# need a server restart (~5 minutes to joinable on Ulfsland). Nothing in this",
        "# tree applies them.",
        "#",
        f"# Baseline (world.yaml baseline.world_modifiers): "
        + ", ".join(f"{k}={v}" for k, v in sorted(world.baseline_modifiers.items())),
    ]
    if changes:
        lines += ["# Preset changes:"] + [f"#   {c}" for c in changes]
    else:
        lines += ["# Preset changes: none -- this preset asks for nothing the baseline does not give."]
    lines += [
        "",
        f"SERVER_ARGS='-preset {world.launch_preset} {args}'",
        "",
    ]
    return "\n".join(lines)


def render_overrides(world: World, preset, policy: dict) -> str:
    rules = applicable_rules(preset, policy)
    doc: list[str] = provenance(world, preset, "Server-config overrides")
    doc += [
        "#",
        "# Each entry is a SINGLE key in a SINGLE section of one deployed config file,",
        "# with the value currently deployed alongside the value this tier wants. Whole",
        "# config files are deliberately not copied here: nine copies of a 700-line file",
        "# is the drift trap this layout exists to avoid.",
        "#",
        f"# Deployed files live under {world.raw.get('server_config_root')} .",
        "# Applying these is an operator action; derive.py never writes a profile.",
        "",
    ]
    body = {
        "world": world.name,
        "preset": preset.name,
        "tier": preset.tier,
        "server_config_root": world.raw.get("server_config_root"),
        "overrides": [
            {
                "id": rule["id"],
                "config": rule["config"],
                "section": rule["section"],
                "key": rule["key"],
                "base": rule["base"],
                "override": value,
                "evidence": rule["evidence"],
                "why": rule["why"],
            }
            for rule, value in rules
        ],
    }
    if not rules:
        body["overrides"] = []
        body["note"] = (
            "No overrides. Every deployed value is already correct for this tier -- "
            "recorded explicitly so the next reader knows this is a decision, not a gap."
        )
    return "\n".join(doc) + yaml.safe_dump(body, sort_keys=False, width=88, allow_unicode=True)


def render_keys(world: World, preset, policy: dict) -> str:
    keys = preset.global_keys
    doc = provenance(world, preset, "Global keys")
    doc += [
        "#",
        "# Global keys are free-form strings that persist in the world DB. They are not",
        "# cosmetic on this server: CLLC reads them (Second factor = BossesKilled),",
        "# ZenWorldSettings gates per-biome spawns on them, ZenRaids appends them to",
        "# player keys, and EpicLoot picks biome loot tables from them with",
        "# `Defer Chest Loot Roll = true`, so every unopened chest in the world rerolls",
        "# at the new key state on first interaction.",
        "#",
        "# Applied by tools/jumpstart/jumpstart.py, one at a time, re-reading globalKeys",
        "# after each so a half-applied chain is diagnosable. Not applied by derive.py.",
        "",
    ]
    body: dict = {
        "world": world.name,
        "preset": preset.name,
        "tier": preset.tier,
        "boss": preset.raw.get("boss"),
        "global_keys": keys,
        "apply": {
            "tool": "tools/jumpstart/jumpstart.py",
            "command": f"jumpstart.py apply {preset.name} --players <steamid> --keys-only --commit",
            "order": "as listed; the driver reads globalKeys back after each key",
        },
    }
    warnings: list[str] = []
    if not keys:
        warnings.append(
            "This preset sets NO keys. That is correct for tier 1 and it is also what "
            "makes tier 1 safe: almost every raid and every high-tier spawn is key-gated."
        )
    if "defeated_frozenking_p3" in keys:
        warnings.append(
            "defeated_frozenking_p3 is INFERRED spelling. It has never been observed set "
            "on this fleet. Do not apply it blind -- confirm it against the game's own "
            "GlobalKeys data first; a misspelled key silently persists in the world DB "
            "and cannot be distinguished from a real one."
        )
    if len(keys) >= 6:
        warnings.append(
            "CLLC world level is driven by boss keys and saturates at 6, so this preset "
            "maxes the creature-level curve world-wide and immediately, including in "
            "Meadows. settings/overrides.yaml lowers CLLC Difficulty to compensate."
        )
    if "defeated_fader" in keys:
        warnings.append(
            "defeated_fader adds no further CLLC difficulty (the curve is already "
            "saturated) but is the sharpest early-biome spawn offender. It is blocked in "
            "Meadows through Mistlands by ZenWorldSettings; Ocean is the hole, which is "
            "why tiers 7-8 override `Ocean - Blocked Keys`."
        )
    if warnings:
        body["warnings"] = warnings
    return "\n".join(doc) + yaml.safe_dump(body, sort_keys=False, width=88, allow_unicode=True)


def render_chest_manifest(world: World, preset, part: Partition, capacity: int | None) -> str:
    doc = provenance(world, preset, "Chest manifest (template overflow)")
    chest_slots = 32
    implied = -(-part.overflow_slots // chest_slots) if part.overflow_slots else 0
    doc += [
        "#",
        "# What the ServerCharacters template CANNOT carry. ServerCharacters grants items",
        "# with Inventory.AddItem, which returns null once the grid is full, and the mod",
        "# ignores the return -- so anything past the last free slot vanishes silently.",
        f"# This world's grid is {world.slots} slots (world.yaml inventory.slots).",
        "#",
        "# Delivery is headless and does not need the player online, per BlueprintHunt:",
        "#   findObjects -prefab piece_chest -near <x> <y> <z> <r>   -> ZDO ids",
        "#   addItemToContainer <id:userid> <item_name> -count <n>   -> stock each chest",
        "# Chest inventories are separate grids, so this sidesteps the truncation above.",
        "# Caveat: RCON responses hard-truncate at 4050 payload bytes and findObjects has",
        "# no pagination, so keep the -near radius tight on a populated world.",
        "# Alternative: a base hand-built and saved from the ulfsland-admin seat with",
        "# Infinity Hammer `hammer_save data=true` carries its chest contents in the",
        "# blueprint, which makes this manifest unnecessary for that preset.",
        "",
    ]
    body: dict = {
        "world": world.name,
        "preset": preset.name,
        "tier": preset.tier,
        "carried_by_template_slots": part.carried_slots,
        "inventory_slots": world.slots,
        "overflow_slots": part.overflow_slots,
        "implied_chests_at_32_slots": implied,
        "items": {p: part.overflow[p] for p in sorted(part.overflow)},
    }
    if capacity is not None:
        body["placed_chest_slots"] = capacity
        if part.overflow_slots > capacity:
            body["capacity_shortfall_slots"] = part.overflow_slots - capacity
            body["action"] = (
                "Placed chest capacity is smaller than the overflow. BlueprintHunt adds a "
                "standalone storage blueprint to this preset's placement rather than "
                "dropping items."
            )
    else:
        body["placed_chest_slots"] = None
        body["note"] = (
            "placements.yaml reports no `containers:` block yet, so placed capacity is "
            "unknown and no shortfall check was made."
        )
    if part.unknown:
        body["stack_size_unknown"] = part.unknown
        body["stack_size_unknown_note"] = (
            "Neither the deployed ItemStacksRewrite table nor world.yaml's "
            "inventory.stack_fallbacks covers these, so their slot cost was counted as one "
            "slot per item -- an over-estimate, which errs towards the chest."
        )
    return "\n".join(doc) + yaml.safe_dump(body, sort_keys=False, width=88, allow_unicode=True)


def render_template(world: World, preset, part: Partition, spawn: list[dict]) -> str:
    sc = world.raw.get("servercharacters") or {}
    omit = dict((world.raw.get("skills") or {}).get("omit") or {})
    skills = {
        name: level
        for name, level in sorted(preset.skills.items())
        if level and name not in omit
    }
    dropped_inert = sorted(n for n in omit if preset.skills.get(n))
    quality_lost = sorted({str(r["prefab"]) for r in preset.raw.get("kit") or [] if int(r.get("quality", 1)) > 1})

    lines = provenance(world, preset, "ServerCharacters CharacterTemplate.yml")
    lines += [
        "#",
        f"# REQUIRES ServerCharacters {sc.get('requires_version')} or newer. 1.4.16 must NOT be",
        "# installed: it hard-fails on Valheim 1.0.12 and ServerSync rejects it against a",
        f"# {sc.get('requires_version')} server.",
        f"# STATUS: {sc.get('status')} -- see world.yaml servercharacters.status_note.",
        "#",
        "# Install: copy this file to",
        f"#   {sc.get('durable_path')}",
        "# The server watches it and live-reloads; no restart. One server holds ONE",
        "# template, so exactly one preset is active at a time.",
        "#",
        "# APPLIES TO NEW CHARACTERS ONLY. The client wipes inventory, skills, known",
        "# recipes and stations, calls GiveDefaultItems(), then applies this. An existing",
        "# character sees nothing.",
        "#",
        "# Exactly three top-level keys are permitted. The deserializer is built with",
        "# IgnoreFields() and the only catch is for SerializationException, which does not",
        "# catch YamlDotNet's YamlException -- so an unknown top-level key throws out of a",
        "# Harmony prefix. Comments are safe; extra keys are not.",
        "#",
        "# What this format drops, and where it went instead:",
        f"#   quality     AddItem hardcodes 1. {len(quality_lost)} kit entries ask for quality > 1 and",
        "#               arrive unupgraded; they must be upgraded at the station.",
        f"#   overflow    {len(part.overflow)} prefabs ({part.overflow_slots} slots) do not fit in "
        f"{world.slots} inventory slots",
        "#               and are in settings/chest-manifest.yaml instead.",
        "#   stations    buildings, not inventory -- blueprints/ and placements.yaml.",
        "#   keys        world state, not character state -- keys.yaml.",
        "#   modifiers   launch arguments -- settings/world-modifiers.env.",
        "#   equipping   nothing is auto-equipped; the kit arrives in the bag.",
        "#",
        "# Which of these skills actually move yield (MEASURED by YieldDesign). Five",
        "# skills drive the gathering economy and three of them are custom skills",
        "# registered by name through SkillManager, not members of the vanilla enum:",
        "#   ore / stone   Smoothbrain `Mining` AND vanilla `Pickaxes` -- ImpactfulSkills'",
        "#                 mining bonus reads vanilla Pickaxes (id 12). Both are needed.",
        "#   wood          Smoothbrain `Lumberjacking` only. Vanilla `WoodCutting` is",
        "#                 DELIBERATELY OMITTED below, not forgotten, and it is DOUBLY",
        "#                 dead: Lumberjacking prefixes CheatRaiseSkill with",
        "#                 RemoveWoodcuttingFromSkillFunctions, which rewrites the",
        "#                 literal to \"Woodcutting \" so it matches nothing, and also",
        "#                 prefixes GetSkill with ReturnDummyWoodcuttingSkill so any",
        "#                 raise that got through lands on a throwaway object.",
        "#                 ImpactfulSkills' WoodCuttingLootFactor = 3 is dead code.",
        "#                 Do not add it back.",
        "#   berries etc   Smoothbrain `Foraging` AND vanilla `Farming`.",
        "#   crops         vanilla `Farming` only -- Smoothbrain Foraging's scope",
        "#                 predicate needs Pickable.m_respawnTimeMinutes > 0 and crops are 0.",
        "#   meat / hide   no skill at all; flat, at whatever the world resource rate is.",
        "#",
        "# Can this map REACH the custom skills? YES, all five, by plain name,",
        "# case-insensitively. Established twice and independently: from the IL of",
        "# assembly_valheim.dll and the deployed plugins, and from the live SkillManager",
        "# registries and Harmony patch chain on a booted server. The two agree.",
        "#   vanilla   Skills::.cctor sets s_allSkills = Enum.GetValues(SkillType) and",
        "#             CheatRaiseSkill string-matches SkillType.ToString() against it, so",
        "#             unaided it reaches enum members only. m_level += value, clamped",
        "#             0..100 -- an ADD, so a set on a fresh character but it would",
        "#             STACK if the template were applied twice.",
        "#   custom    Each Smoothbrain plugin ILRepacks its own SkillManager, which",
        "#             Harmony-PREFIXES CheatRaiseSkill with Patch_Skills_CheatRaiseskill.",
        "#             It matches its registry's `internalSkillName` with",
        "#             StringComparison.CurrentCultureIgnoreCase and returns false to",
        "#             consume the call, else true and the chain continues. Three",
        "#             independent prefixes, each matching only its own skill, so there",
        "#             is no ordering hazard.",
        "#   ids       Not enum members, so the prefix is the ONLY route: Mining =",
        "#             1408976878, Foraging = 47719919, Lumberjacking = 1363793286,",
        "#             each (SkillType)englishName.GetStableHashCode().",
        "#   literal   internalSkillName = Regex.Replace(englishName, \"[^a-zA-Z]\", \"_\").",
        "#             Registered english names are literally Mining / Foraging /",
        "#             Lumberjacking -- pure alpha, so internal == display == what you",
        "#             type. The exact casing below is the registered casing.",
        "#   where     Applied CLIENT-side, in ServerCharacters.ClientSide",
        "#             .InitializePlayerFromTemplate.Postfix, so the three Smoothbrain",
        "#             mods must reach the client. They do -- all four are scope: shared",
        "#             in the ulfsland-dn manifest.",
        "#   trap      A matching prefix consumes the call, so a custom skill whose name",
        "#             collides with a vanilla one captures it. Smoothbrain-Farming did",
        "#             exactly that and was removed tonight; re-adding it would silently",
        "#             change what the `Farming` line below means.",
        "# `Farming` is RESOLVED: vanilla SkillType Farming is 0x6a = 106 in this build",
        "# and there is no id 15 at all. ImpactfulSkills contains no SkillManager",
        "# reference and reads GetSkillLevel(0x6a) -- vanilla Farming. Exactly one",
        "# Farming exists and this line reaches it. ImpactfulSkills' OWN custom skills",
        "# (Hauling, Voyager) are not template-settable; neither drives yield.",
        "",
    ]

    lines.append("skills:")
    if skills:
        for name, level in skills.items():
            lines.append(f"  {name}: {float(level)}")
        zero = sum(1 for level in preset.skills.values() if not level)
        lines.append(
            f"# {zero} skills omitted at level 0: CheatRaiseSkill(name, 0) is a no-op, and an"
        )
        lines.append("# unresolvable name is logged and skipped, not fatal.")
        for name in dropped_inert:
            lines.append(
                f"# {name} omitted at {preset.skills[name]} on purpose -- inert on this mod set,"
            )
            lines.append("# see world.yaml skills.omit. Re-adding it does nothing.")
    else:
        lines.append("  {}")

    lines.append("items:")
    if part.carried:
        for prefab in sorted(part.carried):
            lines.append(f"  {prefab}: {part.carried[prefab]}")
        lines.append(f"# {part.carried_slots} of {world.slots} inventory slots used.")
        if part.dupes:
            lines.append(
                "# Summed across buckets (the preset lists these twice, and `items` is a map): "
                + ", ".join(part.dupes)
            )
    else:
        lines.append("  {}")

    lines.append("spawn:")
    if spawn:
        emitted = list(spawn)
        if len(emitted) > 1:
            # Random.Range(0, count - 1) has an EXCLUSIVE upper bound, so the last
            # entry is never selected. Duplicating it makes every real point
            # reachable. spawn.yaml lists real points only.
            emitted.append(dict(emitted[-1]))
        for point in emitted:
            lines.append(f"  - {{x: {point['x']}, y: {point['y']}, z: {point['z']}}}")
        if len(spawn) > 1:
            lines.append(
                "# Last entry is a deliberate duplicate: selection is "
                "Random.Range(0, count - 1),"
            )
            lines.append("# whose upper bound is exclusive, so without it the real last point is dead.")
        lines.append(f"# MEASURED against Valheim's own generator at {SPAWN_PROBE_STEP_M:g} m, "
                     f"water plane y={SEA_LEVEL_M:g}:")
        for point in spawn:
            walk = point.get("approach") or {}
            lines.append(
                f"#   ({point['x']}, {point['y']}, {point['z']})  ground {point['terrain_y']} "
                f"= +{point['spawn_freeboard_m']} m over water, {point['dist_to_footprint_edge_m']} m "
                f"outside {point['base']}'s footprint ({point['dist_to_base_m']} m from its centre),"
            )
            lines.append(
                f"#     dry across a {SPAWN_DISC_R_M:g} m disc (min +{point['disc_min_freeboard_m']} m) "
                f"and dry every metre of the {walk.get('length_m')} m walk to it."
            )
        lines.append(f"# Evidence: {SPAWN_FILE}. Re-verify: derive.py spawn {world.name}")
    else:
        lines.append("  []")
        lines.append(
            "# No spawn: no coordinate next to this preset's base could be PROVEN to be on"
        )
        lines.append(
            f"# land, so the vanilla spawn is left alone. See {SPAWN_FILE} `refused:` for the"
        )
        lines.append(
            "# measured reason. A missing spawn is a visible gap; a wet one reaches the player."
        )

    return "\n".join(lines) + "\n"


# ==========================================================================
# drive
# ==========================================================================
def generate(
    world: World, preset, policy: dict, measured, fallbacks, spawn: list[dict]
) -> dict[str, str]:
    preset_dir = world.root / preset.name
    part = partition(preset, world, measured, fallbacks)
    capacity = load_container_capacity(load_placements(preset_dir))
    return {
        "settings/world-modifiers.env": render_modifiers(world, preset, policy),
        "settings/overrides.yaml": render_overrides(world, preset, policy),
        "settings/chest-manifest.yaml": render_chest_manifest(world, preset, part, capacity),
        "keys.yaml": render_keys(world, preset, policy),
        "charactertemplate.yml": render_template(world, preset, part, spawn),
    }


def run(world_name: str, preset_names: list[str] | None, write: bool) -> int:
    world = load_world(world_name)
    policy = load_policy()
    measured, fallbacks = load_stacks(world)
    if not measured:
        print(
            f"warning: stack table {world.stack_table_path} not readable; "
            "slot costs fall back to one slot per item",
            file=sys.stderr,
        )
    names = preset_names or js.all_preset_names()

    drift = 0
    for name in names:
        preset = js.load_preset(name)
        preset_dir = world.root / name
        placements = load_placements(preset_dir)
        spawn, problems = audit_spawn(world, preset, placements, load_spawn_file(preset_dir))
        files = generate(world, preset, policy, measured, fallbacks, spawn)
        if problems:
            # The template is the only file that carries a coordinate, so it is
            # the only one held back: shipping a spawn whose terrain verdict no
            # longer applies is the failure this check exists to stop.
            files.pop("charactertemplate.yml")
            for problem in problems:
                print(f"SPAWN    {problem}", file=sys.stderr)
            drift += len(problems)
            print(f"{'HELD':8s} {world.name}/{name}/charactertemplate.yml")
        for rel, content in files.items():
            path = preset_dir / rel
            current = path.read_text("utf-8") if path.exists() else None
            if current == content:
                status = "ok"
            elif write:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(content, "utf-8")
                status = "wrote" if current is None else "updated"
            else:
                status = "DRIFT" if current is not None else "MISSING"
                drift += 1
            print(f"{status:8s} {world.name}/{name}/{rel}")
        if write:
            # Owned by BlueprintHunt. Created so the layout is complete; never
            # written into, never cleaned.
            (preset_dir / "blueprints").mkdir(parents=True, exist_ok=True)
    if drift:
        print(f"\n{drift} problem(s): files differ from what the inputs derive.", file=sys.stderr)
        return 1
    return 0


def run_spawn(
    world_name: str,
    preset_names: list[str] | None,
    vh_src: str | None,
    patch_path: Path,
    sandbox: str | None,
    reuse: bool,
    write: bool,
) -> int:
    """Probe terrain and (re)write spawn.yaml. The only mode that needs a server."""
    sf = _site_finder()
    world = load_world(world_name)
    seed = str(world.raw.get("seed") or "")
    if not seed:
        raise SystemExit(f"{world.root / 'world.yaml'}: no `seed`, so terrain cannot be probed")
    presets = [js.load_preset(n) for n in (preset_names or js.all_preset_names())]
    rows = patch_rows(world, presets)
    if not rows:
        print("no solved placements to derive a spawn from", file=sys.stderr)
        return 1

    patches: dict[str, dict] = {}
    if patch_path.exists():
        patches = sf.load_patches(patch_path)
    if not patch_covers(rows, patches):
        if reuse:
            raise SystemExit(
                f"{patch_path} does not cover the {len(rows)} window(s) this run needs; "
                "drop --reuse-patch to re-probe"
            )
        if not vh_src:
            raise SystemExit(
                "terrain probe needs a server install: pass --vh-src (or set VH_SRC) to "
                "<VALHEIM_ROOT>/<World>/data/bepinex. It runs in an rsync'd sandbox on its "
                "own port and savedir; nothing live is touched."
            )
        print(
            f"probing {len(rows)} window(s) at {SPAWN_PROBE_STEP_M:g} m for seed {seed}",
            file=sys.stderr,
        )
        run_patchscan(seed, rows, patch_path, vh_src, sandbox)
        patches = sf.load_patches(patch_path)
        if not patch_covers(rows, patches):  # pragma: no cover - defensive
            raise SystemExit(f"{patch_path}: probe did not return the requested windows")

    drift = 0
    for preset in presets:
        preset_dir = world.root / preset.name
        placements = load_placements(preset_dir)
        results = [
            probe_spawn(patches[f"{preset.name}#{pid}"], pl)
            for pid, pl in sorted(solved_placements(placements).items())
        ]
        for r in results:
            if "point" in r:
                p = r["point"]
                print(
                    f"  OK  {preset.name:18} {p['base']:26} -> ({p['x']}, {p['y']}, {p['z']}) "
                    f"ground={p['terrain_y']} (+{p['spawn_freeboard_m']} m) "
                    f"edge={p['dist_to_footprint_edge_m']}m base={p['dist_to_base_m']}m "
                    f"disc=+{p['disc_min_freeboard_m']}m score={p['score']}"
                )
            else:
                print(f"  !!  {preset.name:18} {r['base']:26} -> NO SPAWN: {r['refused']}")
        content = render_spawn(world, preset, results)
        path = preset_dir / SPAWN_FILE
        current = path.read_text("utf-8") if path.exists() else None
        if current == content:
            status = "ok"
        elif write:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, "utf-8")
            status = "wrote" if current is None else "updated"
        else:
            status = "DRIFT" if current is not None else "MISSING"
            drift += 1
        print(f"{status:8s} {world.name}/{preset.name}/{SPAWN_FILE}")
    if drift:
        print(
            f"\n{drift} {SPAWN_FILE} file(s) disagree with a fresh terrain probe.",
            file=sys.stderr,
        )
        return 1
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = parser.add_subparsers(dest="cmd", required=True)
    sub.add_parser("list", help="list worlds and presets")
    for cmd, help_text in (("build", "write the tree"), ("check", "re-derive and diff, never write")):
        p = sub.add_parser(cmd, help=help_text)
        p.add_argument("world")
        p.add_argument("--preset", action="append", dest="presets")
    sp = sub.add_parser(
        "spawn",
        help=f"probe terrain and rewrite {SPAWN_FILE} (boots a sandboxed server)",
    )
    sp.add_argument("world")
    sp.add_argument("--preset", action="append", dest="presets")
    sp.add_argument(
        "--vh-src",
        default=os.environ.get("VH_SRC"),
        help="server install dir (<VALHEIM_ROOT>/<World>/data/bepinex); the probe runs in an "
        "rsync'd sandbox copy on its own port and savedir",
    )
    sp.add_argument("--patch", help="patch dump path (written by run_patchscan.sh)")
    sp.add_argument("--patch-sandbox", help="sandbox dir for run_patchscan.sh")
    sp.add_argument(
        "--reuse-patch", action="store_true", help="reuse an existing --patch instead of re-probing"
    )
    sp.add_argument(
        "--check",
        action="store_true",
        help=f"re-probe and diff, never write: exits 1 when {SPAWN_FILE} disagrees with terrain",
    )

    args = parser.parse_args(argv)
    if args.cmd == "list":
        worlds = sorted(p.parent.name for p in HERE.glob("*/world.yaml"))
        print("worlds:  " + (", ".join(worlds) or "(none)"))
        print("presets: " + ", ".join(js.all_preset_names()))
        print(f"owned:   {', '.join(OWNED)}")
        print(f"         {SPAWN_FILE}  (written by `spawn`, read by build/check)")
        print("other:   blueprints/, placements.yaml  (BlueprintHunt)")
        return 0
    if args.cmd == "spawn":
        default_patch = Path("/tmp/jumpstart-spawn") / f"patch-{args.world}.bin"
        return run_spawn(
            args.world,
            args.presets,
            args.vh_src,
            Path(args.patch) if args.patch else default_patch,
            args.patch_sandbox,
            reuse=args.reuse_patch,
            write=not args.check,
        )
    return run(args.world, args.presets, write=(args.cmd == "build"))


if __name__ == "__main__":
    raise SystemExit(main())
