<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>ServerCharacters</AssemblyName>
    <RootNamespace>ServerCharacters</RootNamespace>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <DebugType>none</DebugType>
    <Optimize>true</Optimize>
    <Deterministic>true</Deterministic>
    <NoWarn>MSB3277;CS0436;CS8632</NoWarn>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <RefDir>$(MSBuildProjectDirectory)/refs</RefDir>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="ClientSide.cs" />
    <Compile Include="Enums.cs" />
    <Compile Include="PlayerTemplate.cs" />
    <Compile Include="Request.cs" />
    <Compile Include="ServerCharacters.cs" />
    <Compile Include="ServerSide.cs" />
    <Compile Include="Shared.cs" />
    <Compile Include="Utils.cs" />
    <Compile Include="WebInterfaceAPI.cs" />
    <Compile Include="Properties/AssemblyInfo.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
    <PackageReference Include="protobuf-net" Version="3.2.26" />
    <PackageReference Include="YamlDotNet" Version="13.7.1" />
    <PackageReference Include="ILRepack.Lib.MSBuild.Task" Version="2.0.34.2" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="ServerSync"><HintPath>Libs/ServerSync.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="System.IO.Compression"><HintPath>Libs/System.IO.Compression.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="System.IO.Compression.FileSystem"><HintPath>Libs/System.IO.Compression.FileSystem.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="System.IO.Compression.ZipFile"><HintPath>Libs/System.IO.Compression.ZipFile.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="0Harmony"><HintPath>$(RefDir)/0Harmony.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="BepInEx"><HintPath>$(RefDir)/BepInEx.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="assembly_valheim"><HintPath>$(RefDir)/assembly_valheim_publicized.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="assembly_utils"><HintPath>$(RefDir)/assembly_utils_publicized.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="assembly_guiutils"><HintPath>$(RefDir)/assembly_guiutils_publicized.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="com.rlabrecque.steamworks.net"><HintPath>$(RefDir)/com.rlabrecque.steamworks.net_publicized.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="SoftReferenceableAssets"><HintPath>$(RefDir)/SoftReferenceableAssets_publicized.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Splatform"><HintPath>$(RefDir)/Splatform.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Unity.TextMeshPro"><HintPath>$(RefDir)/Unity.TextMeshPro.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine"><HintPath>$(RefDir)/UnityEngine.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.CoreModule"><HintPath>$(RefDir)/UnityEngine.CoreModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.UI"><HintPath>$(RefDir)/UnityEngine.UI.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.IMGUIModule"><HintPath>$(RefDir)/UnityEngine.IMGUIModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.InputLegacyModule"><HintPath>$(RefDir)/UnityEngine.InputLegacyModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.PhysicsModule"><HintPath>$(RefDir)/UnityEngine.PhysicsModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.TextRenderingModule"><HintPath>$(RefDir)/UnityEngine.TextRenderingModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.UIModule"><HintPath>$(RefDir)/UnityEngine.UIModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.AnimationModule"><HintPath>$(RefDir)/UnityEngine.AnimationModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.AudioModule"><HintPath>$(RefDir)/UnityEngine.AudioModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.ImageConversionModule"><HintPath>$(RefDir)/UnityEngine.ImageConversionModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.ParticleSystemModule"><HintPath>$(RefDir)/UnityEngine.ParticleSystemModule.dll</HintPath><Private>false</Private></Reference>
  </ItemGroup>

</Project>
