#!/usr/bin/env python3
"""Merge a server's setting overrides over a profile's canonical settings.

A mod profile is shared: several servers run the same mod set, and its settings are the
profile's, edited once. A server may still need one value of its own - the address a
link mod advertises, a world-specific tuning - so it may override *settings*, never the
mod list.

The merge is per KEY, not per file. Whole-file overrides look simpler and are the reason
this exists: overriding one line meant copying a 700-line config, and the copy then
silently kept the old defaults for every other setting when the profile moved on. That
is the same drift that left four worlds with four different mod sets.

BepInEx writes an INI dialect:

    ## Settings file was created by plugin WardIsLove v3.7.2
    [Section Name]
    # Setting type: Boolean
    Key = Value

Comments beginning `##` describe the file, `#` describes the following key, and both are
regenerated by the plugin. The merge keeps the profile's text - comments, order, spacing
- and replaces only the values a server overrides, so a diff against the profile shows
exactly what that server changed and nothing else.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

SECTION_SUFFIX = "]"


def parse(text: str) -> dict[tuple[str, str], str]:
    """Every ``(section, key) -> value`` in one config.

    Keys outside any section are held under the empty section, which is what BepInEx
    writes for a file with no sections rather than an error.
    """
    values: dict[tuple[str, str], str] = {}
    section = ""
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if stripped.startswith("[") and stripped.endswith(SECTION_SUFFIX):
            section = stripped[1:-1]
            continue
        key, separator, value = line.partition("=")
        if not separator:
            continue
        values[(section, key.strip())] = value.strip()
    return values


def merge(base: str, override: str) -> str:
    """``base`` with the values from ``override`` applied, keeping base's text.

    A key the base does not define is appended under its section, with a marker comment,
    because a server that needs a setting the profile never wrote still needs it to
    reach the file. A section the base does not have is appended whole.
    """
    wanted = parse(override)
    if not wanted:
        return base

    applied: set[tuple[str, str]] = set()
    out: list[str] = []
    section = ""
    pending_section_end = -1

    for line in base.splitlines():
        stripped = line.strip()
        if stripped.startswith("[") and stripped.endswith(SECTION_SUFFIX):
            out.extend(_appended(wanted, applied, section))
            section = stripped[1:-1]
            out.append(line)
            continue
        key, separator, _ = line.partition("=")
        if separator and not stripped.startswith("#"):
            name = key.strip()
            if (section, name) in wanted:
                out.append(f"{key.rstrip()} = {wanted[(section, name)]}")
                applied.add((section, name))
                continue
        out.append(line)
    out.extend(_appended(wanted, applied, section))

    # Whole sections the profile never wrote.
    remaining = [entry for entry in wanted if entry not in applied]
    for missing_section in dict.fromkeys(entry[0] for entry in remaining):
        out.append("")
        if missing_section:
            out.append(f"[{missing_section}]")
        for entry in remaining:
            if entry[0] == missing_section:
                out.append("## server override")
                out.append(f"{entry[1]} = {wanted[entry]}")
    text = "\n".join(out)
    return text if text.endswith("\n") else text + "\n"


def _appended(wanted, applied, section) -> list[str]:
    """Keys of ``section`` the base did not define, emitted before the next section."""
    lines: list[str] = []
    for (entry_section, name), value in wanted.items():
        if entry_section == section and (entry_section, name) not in applied:
            lines.append("## server override")
            lines.append(f"{name} = {value}")
            applied.add((entry_section, name))
    return lines


def merge_tree(base_dir: Path, override_dir: Path, out_dir: Path) -> list[str]:
    """Write ``base_dir`` into ``out_dir``, applying any same-named override file.

    Returns the files an override touched, so a caller can report what a server changed
    rather than asserting that it changed nothing.
    """
    base_dir, override_dir, out_dir = Path(base_dir), Path(override_dir), Path(out_dir)
    overridden: list[str] = []
    out_dir.mkdir(parents=True, exist_ok=True)
    for source in sorted(base_dir.rglob("*")) if base_dir.is_dir() else []:
        if not source.is_file() or source.is_symlink():
            continue
        relative = source.relative_to(base_dir)
        destination = out_dir / relative
        destination.parent.mkdir(parents=True, exist_ok=True)
        candidate = override_dir / relative
        if candidate.is_file() and source.suffix.lower() == ".cfg":
            destination.write_text(
                merge(source.read_text(encoding="utf-8", errors="replace"),
                      candidate.read_text(encoding="utf-8", errors="replace")),
                encoding="utf-8")
            overridden.append(relative.as_posix())
        elif candidate.is_file():
            # Only the INI dialect can be merged per key. A YAML or JSON override wins
            # whole, and is reported as such: ignoring it would drop a setting the
            # operator wrote, and half-parsing it would produce neither format.
            destination.write_bytes(candidate.read_bytes())
            overridden.append(relative.as_posix() + " (whole file)")
        else:
            destination.write_bytes(source.read_bytes())

    # An override for a file the profile does not have. Copied rather than dropped: the
    # alternative is a setting an operator wrote that never reaches the server, with
    # nothing said about it.
    for source in sorted(override_dir.rglob("*")) if override_dir.is_dir() else []:
        if not source.is_file() or source.is_symlink():
            continue
        relative = source.relative_to(override_dir)
        if (base_dir / relative).is_file():
            continue
        destination = out_dir / relative
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_bytes(source.read_bytes())
        overridden.append(relative.as_posix() + " (override only)")
    return overridden


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    sub = parser.add_subparsers(dest="command", required=True)
    one = sub.add_parser("file", help="merge one override over one config")
    one.add_argument("base", type=Path)
    one.add_argument("override", type=Path)
    tree = sub.add_parser("tree", help="merge a directory of overrides over a directory of configs")
    tree.add_argument("base", type=Path)
    tree.add_argument("override", type=Path)
    tree.add_argument("out", type=Path)
    args = parser.parse_args(argv)

    if args.command == "file":
        sys.stdout.write(merge(args.base.read_text(encoding="utf-8", errors="replace"),
                               args.override.read_text(encoding="utf-8", errors="replace")))
        return 0
    for touched in merge_tree(args.base, args.override, args.out):
        print(touched)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
